export const ROUTES = {
  HOME: '/',
  INDEX: '/',
  BOOK_JOB: '/book-job',
  SOLICITAR_SERVICIO: '/solicitar-servicio',
  USER_LANDING: '/user-landing',
  DASHBOARD_USER: '/dashboard/user',
  USER_AUTH: '/auth/user',
  USER_AUTH_SIGNIN: '/auth/user?mode=signin',
  PROVIDER_AUTH: '/auth/provider',
  PROVIDER_LANDING_OLD: '/provider-landing',
  PROVIDER_ONBOARDING: '/provider-onboarding',
  PROVIDER_PROFILE_OLD: '/provider-profile',
  PROVIDER_LANDING: '/provider-landing',
  PROVIDER_PORTAL: '/provider-portal',
  PROVIDER_DASHBOARD: '/provider-portal/dashboard',
  PROVIDER_JOBS: '/provider-portal/jobs',
  PROVIDER_CALENDAR: '/provider-portal/calendar',
  PROVIDER_MAP: '/provider-portal/map',
  PROVIDER_PROFILE: '/provider-portal/profile',
  PROVIDER_VERIFICATION: '/provider-portal/verification',
  PROVIDER_NOTIFICATIONS: '/provider-portal/notifications',
  BECOME_PROVIDER: '/become-provider',
  PROFILE: '/profile',
  PROFILE_SETTINGS: '/profile/settings',
  PROFILE_SECURITY: '/profile/security',
  PROFILE_GENERAL: '/profile/general',
  PROFILE_LOCATIONS: '/profile/locations',
  PROFILE_DATA_EXPORT: '/profile/data-export',
  PROFILE_ACCOUNT_DELETION: '/profile/account-deletion',
  SECURITY_SETTINGS: '/security-settings',
  SAVED_LOCATIONS: '/saved-locations',
  MOBILE_JOBS: '/mobile-jobs',
  MOBILE_FAVORITES: '/mobile-favorites',
  MOBILE_PROFILE: '/mobile-profile',
  AUTH_CALLBACK: '/auth/callback',
  CALLBACK: '/callback',
  BROWSE_TASKS: '/browse-tasks',
  ACTIVE_JOBS: '/active-jobs',
  FINDING_PROVIDER: '/finding-provider',
  BLOG: '/blog',
  HELP_CENTER: '/help-center',
  CHOOSE_ROLE: '/choose-role',
  NOT_FOUND: '/not-found',
} as const;

export type AppRoute = typeof ROUTES[keyof typeof ROUTES];
